### ISSUE TITLE
hybrid-automaton-tools-py in SoMa

### ISSUE THREAD

**Issue by psotiropoulos** [SoMa-Project/ec_grasp_planner#16]
@zweistein @cerdogan @ptriantd-ocado @hmn-ocado it might make sense to bring the hybrid-automaton-tools-py in the SoMa project. 

There are some configurations in the cookbook.py that might need to be changed per setup (eg. rbo actuation, and safety switces).

**Comment by zweistein** [comment]
We fixed this during the ambassador visit by adding the `hybrid-automaton-tools-py` repository directly to the SOMA organization.

**Comment by psotiropoulos** [comment]
@zweistein Do we still need to keep it as a submodule? What is the benefit of that?

**Comment by zweistein** [comment]
Right now the only benefit is that the clone, tag, and checkout scripts are using the submodule. 
If you wish to move it out from the submodule, the scripts must be updated too. 

Why? do you have any issues with the current setup?

**Comment by psotiropoulos** [comment]
It seems unnecessarily complex... If you want to add another controller on the hybrid_automaton_manager you have to edit the components.py and then you'll have to update both the submodule and the ec_planner repos.

**Comment by zweistein** [comment]
You are right, this is our interface, so different robots can execute the same plan. Do you propose any modification? Do you want to open this issue or maybe a new one?
Right now, we are not focusing on enhancing existing interfaces but to integrate new features and prepare robust demos.
