### ISSUE TITLE
add python-tornado to the list of dependencies

### ISSUE THREAD

**Issue by JannisW** [SoMa-Project/ec_grasp_planner#27]
Since multiobject support the planner requires the presence of tornado.concurrent 
Thus, it should be added to the list of dependencies. If desired you can mention the actual ubuntu package called python-tornado
I'm not sure where to add that (Minimal Dependencies?), otherwise I would have done it myself.

**Comment by zweistein** [comment]
@JessyVision could you please help with this.

**Comment by JannisW** [comment]
dependency was removed
