### ISSUE TITLE
Limit maximum joint velocity during PostGraspRotate

### ISSUE THREAD

**Issue by JannisW** [SoMa-Project/ec_grasp_planner#29]
The trajectory generated by the HA for PostGraspRotate (for a grasped real cucumber) includes a part in which the WAM is moving at least one of its joints quite fast. This results in the max velocity safety being triggered and in case its not, it simply looks scary.

Adding a parameter to handarm_parameters.py to control this behavior would be great. 
Something worth trying out is, if setting a lower vmax in the HA is already solving this issue (would still need to adjustable from the parameter file)

**Comment by zweistein** [comment]
It looks like this will be solved with the kinematic check as the cause is reaching joint limit while executing the action.

**Comment by JannisW** [comment]
kinematics check was merged to master with PR #57 
This problem was also not observed for a long time after changing initial joint configurations. I'll close the issue now. If it will re-appear, we can reopen this.
