### ISSUE TITLE
dictionary for specific objects needs .copy()

### ISSUE THREAD

**Issue by JessyVision** [SoMa-Project/ec_grasp_planner#33]
If a specific object is instantiated from the general `object` we need to apply the `.copy()` function.
This bug effects the `handarm_param.py`!

We need to 2x check that in master and the demo branches have this bugfix, otherwise the tuning of a new object will overwrite all object parameters like:
`self['edge_grasp']['plushtoy'] = self['edge_grasp']['object'].copy()`

**Comment by JannisW** [comment]
I wouldn't call that a bug. It is more the semantic of python ;)
So is this issue intended as a reminder to apply the copy() function or should we add some sanity checks that will trigger (throw an exception) in case something is overwritten?
(One way to do so would be a call to function in the very end that validates that no two configuration refer to the same object)

Btw. There is a similar risk in massflow.py in soma_utils (when defining the synergie). 
To mitigate the problem there, I introduced a convenient method called add() that deals with this problem.

**Comment by zweistein** [comment]
We should keep this in mind and fix all issues if there is any open due to this python feature. 

if the sanity check can be implemented fast (few minutes) then please do so. Thanks.

**Comment by JannisW** [comment]
sanity checks are merged. Can we close the issue now?

**Comment by zweistein** [comment]
yes, thanks for fixing it.
