### ISSUE TITLE
Object mass estimation over timespan, not single measurement.

### ISSUE THREAD

**Issue by JessyVision** [SoMa-Project/ec_grasp_planner#44]
The mass is estimated currently from a single measurement. However, it would be better to estimate it as the average over a timespan.

**Comment by JannisW** [comment]
Averaging over a sliding window was implemented in 76c781163fa86f24e5014b0dcf989eba5685c289. 
c5fc040483afc648f3c6456985cfdec0d4cc6944 brought some important bug fixes. Both are included in the current ocado and disney branch, but not merged into master.

**Comment by JannisW** [comment]
The feature was merged today to master with PR #57
