### ISSUE TITLE
Corner ec frame computation crashes

### ISSUE THREAD

**Issue by ptriantd-ocado** [SoMa-Project/ec_grasp_planner#50]
`ec_frame[:3, :3] = np.hstack((x, y, z))` crashes because the shape on the right-hand side is 1x9 instead of 3x3. This was fixed in a862285b640a5db9109d4dfb92665e3d255e19e6

**Comment by JannisW** [comment]
This resulted from wrongly converting a the function call `np.stack((x, y, z), axis=1)` to a version that does not require a version of numpy that isn't provided in the ubuntu 14.04 packages.

The fix was merged to master with PR #57
