### ISSUE TITLE
Model separation grasp success estimation (apply fix to ocado branch)

### ISSUE THREAD

**Issue by JannisW** [SoMa-Project/ec_grasp_planner#52]
The most recent version of the grasp success estimator had a bug that broke the difference mass model in case the robot noise was too big. 
The difference model was clearly separated from the absolute model and the problem was fixed in
c5fc040483afc648f3c6456985cfdec0d4cc6944 and https://github.com/SoMa-Project/soma_utils/commit/759068041dfe96d4f18515827f82bcca5f55dc8f

This is merged into tub_ocado_merge and should be propagated to your branches as well (This should not require any manual merging in case of a git cherry-pick of the commits...)

**Comment by ptriantd-ocado** [comment]
Thanks! We have propagated the changes to our branches...
