### ISSUE TITLE
service [/check_kinematics] unavailable

### ISSUE THREAD

**Issue by ninafiona** [SoMa-Project/ec_grasp_planner#63]
Ubuntu 18.04 - ros melodic - tub_feasibility_check on branch master - ec_grasp_planner on branch migration_1804 (from IROS2020)

When calling the service run_grasp_planner I get the following error:
```
rosservice call /run_grasp_planner "{object_type: 'apple', grasp_type: 'Any', handarm_type: 'RBOHandP24_pulpyWAM', object_heuristic_function: 'Deterministic', angle_of_attack: 0.0, wrist_angle: 0.0}"
ERROR: service [/run_grasp_planner] responded with an error: service cannot process request: service [/check_kinematics] unavailable
```
In planner.py line 222, multi_object_params.py line 365.

**Comment by zweistein** [comment]
This functionality requires the `tub_feasibility_checker`. 
To turn off this feature, you need to set on the ROS param server the `heuristic_type`.  You can do that in the [parameter.launch](https://github.com/SoMa-Project/soma_utils/blob/IRSO2020/planner_gui/launch/parameters.launch) from 'panner_gui' pkg by `    <arg name="heuristic_type" default="basic-separated"/>`

**Comment by ninafiona** [comment]
Thank you, it worked with `<param name="planner_gui/heuristic_type" value="basic-separated"/>`
